MNEMONIC: invite adult amount position enable edge song episode cross cotton stand purse

EVM:
  NETWORK: ETH_SEPOLIA
  INSCRIPTION_DATA: data:,{"p":"fair-20","op":"mint","tick":"fair","amt":"1000"}

EVM_NETWORKS:
  ETH_MAINNET: https://eth-mainnet.g.alchemy.com/v2/...
  ETH_SEPOLIA: https://eth-sepolia.g.alchemy.com/v2/...
  BSC_MAINNET: https://bsc-dataseed.binance.org
  ETHW: https://mainnet.ethereumpow.org
