MNEMONIC: "invite adult amount position enable edge song episode cross cotton stand purse"

ALCHEMY_API_KEY: ""


EVM:
  NETWORK: "SEPOLIA"
  INSCRIPTION_DATA: data:,{"p":"fair-20","op":"mint","tick":"fair","amt":"1000"}

EVM_NETWORKS:
  MAINNET: "https://eth-mainnet.g.alchemy.com/v2/<...>"
  SEPOLIA: "https://eth-sepolia.g.alchemy.com/v2/<...>"
  GOERLI: "https://eth-goerli.alchemyapi.io/v2/<...>"
  ETHW: "https://mainnet.ethereumpow.org"

EVM_CONTRACT:
  ERC20: ""
  ERC721: ""
  ERC1155: ""

EVM_ADDRESS:
  TARGET: ""
  SOURCE: ""
